/*
 * strategie.c
 *
 * "avec manche(s)"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 18:09 on 25/09/2021.
 */

#include <strategie.h>

int nb_points = 24;

CONSIGNE consigneBleu[24] = {
    {
      .x = 125, .y = 1326, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 257, .y = 1326, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 478, .y = 1264, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 349, .y = 1621, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 351, .y = 1859, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 351, .y = 1790, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 501, .y = 1821, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 837, .y = 1839, .dir = FORWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 571, .y = 1807, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 882, .y = 1689, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 218, .y = 1469, .dir = FORWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 362, .y = 1519, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 322, .y = 1502, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, FALSE, TRUE },
      .bras = FALSE
    }, {
      .x = 410, .y = 1530, .dir = FORWARD,
      .pinces = { TRUE, FALSE, FALSE, TRUE },
      .bras = FALSE
    }, {
      .x = 206, .y = 1078, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 249, .y = 1177, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 707, .y = 1124, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 667, .y = 925, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 192, .y = 419, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 192, .y = 192, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 252, .y = 173, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 557, .y = 173, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 690, .y = 221, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 274, .y = 792, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }
};

CONSIGNE consigneJaune[24] = {
    {
      .x = 2875, .y = 1326, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2743, .y = 1326, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2522, .y = 1264, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2651, .y = 1621, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2649, .y = 1859, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2649, .y = 1790, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2499, .y = 1821, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2163, .y = 1839, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2429, .y = 1807, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2118, .y = 1689, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 2782, .y = 1469, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2638, .y = 1519, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2678, .y = 1502, .dir = FORWARD,
      .pinces = { FALSE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2590, .y = 1530, .dir = FORWARD,
      .pinces = { FALSE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2794, .y = 1078, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2751, .y = 1177, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2293, .y = 1124, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2333, .y = 925, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2808, .y = 419, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 2808, .y = 192, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 2748, .y = 173, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 2443, .y = 173, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 2310, .y = 221, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }, {
      .x = 2726, .y = 792, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = TRUE
    }
};
