/*
 * strategie.c
 *
 * "test"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 12:52 on 25/09/2021.
 */

#include <strategie.h>

int nb_points = 27;

CONSIGNE consigneBleu[27] = {
    {
      .x = 125, .y = 1326, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 257, .y = 1326, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 478, .y = 1264, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 349, .y = 1621, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 349, .y = 1850, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 351, .y = 1790, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 501, .y = 1821, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 837, .y = 1839, .dir = FORWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 571, .y = 1807, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 882, .y = 1689, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 218, .y = 1469, .dir = FORWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 362, .y = 1519, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 322, .y = 1502, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, FALSE, TRUE },
      .bras = FALSE
    }, {
      .x = 410, .y = 1530, .dir = FORWARD,
      .pinces = { TRUE, FALSE, FALSE, TRUE },
      .bras = FALSE
    }, {
      .x = 206, .y = 1078, .dir = BACKWARD,
      .pinces = { TRUE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 249, .y = 1177, .dir = FORWARD,
      .pinces = { TRUE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 475, .y = 1129, .dir = FORWARD,
      .pinces = { TRUE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 339, .y = 755, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 288, .y = 623, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1063, .y = 1109, .dir = FORWARD,
      .pinces = { TRUE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1637, .y = 518, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1804, .y = 530, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1804, .y = 343, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1804, .y = 434, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1804, .y = 283, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1804, .y = 589, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 325, .y = 688, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};

CONSIGNE consigneJaune[27] = {
    {
      .x = 2875, .y = 1326, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2743, .y = 1326, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2522, .y = 1264, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2651, .y = 1621, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2651, .y = 1850, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2649, .y = 1790, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2499, .y = 1821, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2163, .y = 1839, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2429, .y = 1807, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2118, .y = 1689, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 2782, .y = 1469, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2638, .y = 1519, .dir = FORWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2678, .y = 1502, .dir = FORWARD,
      .pinces = { FALSE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2590, .y = 1530, .dir = BACKWARD,
      .pinces = { FALSE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2794, .y = 1078, .dir = FORWARD,
      .pinces = { FALSE, FALSE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2751, .y = 1177, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2525, .y = 1129, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 2661, .y = 755, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2712, .y = 623, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1937, .y = 1109, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, FALSE },
      .bras = FALSE
    }, {
      .x = 1363, .y = 518, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1196, .y = 530, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, TRUE, TRUE },
      .bras = FALSE
    }, {
      .x = 1196, .y = 343, .dir = BACKWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1196, .y = 434, .dir = FORWARD,
      .pinces = { TRUE, TRUE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1196, .y = 283, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1196, .y = 589, .dir = BACKWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2675, .y = 688, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};
