/*
 * strategie.c
 *
 * "Rotation"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 01:00 on 10/07/2021.
 */

#include <strategie.h>

int nb_points = 3;

CONSIGNE consigneBleu[3] = {
    {
      .x = 125, .y = 1070, .dir = FORWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 550, .y = 1070, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 550, .y = 870, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};

CONSIGNE consigneJaune[3] = {
    {
      .x = 2875, .y = 1070, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2400, .y = 1070, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 2400, .y = 970, .dir = BACKWARD, 
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};
