/*
 * strategie.c
 *
 * "Rotation"
 *
 * Generated by Ares ENSEA Simulator.
 * https://ares.asso-ensea.fr/simulateur/
 * 
 * Created at 01:00 on 10/07/2021.
 */

#include <strategie.h>

int nb_points = 2;

CONSIGNE consigneBleu[2] = {
    {
      .x = 0, .y = 0, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }, {
      .x = 1000, .y = 0, .dir = FORWARD,
      .pinces = { FALSE, FALSE, FALSE, FALSE },
      .bras = FALSE
    }
};

CONSIGNE consigneJaune[2] = {
	    {
	      .x = 0, .y = 0, .dir = FORWARD,
	      .pinces = { FALSE, FALSE, FALSE, FALSE },
	      .bras = FALSE
	    }, {
	      .x = 1000, .y = 0, .dir = FORWARD,
	      .pinces = { FALSE, FALSE, FALSE, FALSE },
	      .bras = FALSE
	    }
};
